//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public System.Guid BookingID { get; set; }
        public Nullable<System.Guid> FlightID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string Seat { get; set; }
    }
}
